// Parse the traced sigil SVG into per-mark data the hero can animate.
// Usage: node scripts/build-sigil.mjs <input.svg>
import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync(process.argv[2], 'utf8');
const viewBox = src.match(/viewBox="([^"]+)"/)[1];
const ds = [...src.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);

function stats(d) {
  const nums = d.match(/-?\d+(\.\d+)?/g).map(Number);
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (let i = 0; i < nums.length; i += 2) {
    const x = nums[i], y = nums[i + 1];
    if (x < minX) minX = x;
    if (x > maxX) maxX = x;
    if (y < minY) minY = y;
    if (y > maxY) maxY = y;
  }
  return {
    cx: (minX + maxX) / 2,
    cy: (minY + maxY) / 2,
    w: maxX - minX,
    h: maxY - minY,
  };
}

const marks = ds.map((d, i) => ({ id: i, d, ...stats(d) }));

// Seal pieces are hand-picked ids (via public/picker.html).
const [, , vw, vh] = viewBox.split(/\s+/).map(Number);
const SEAL_IDS = new Set(
  (process.argv[3] ?? '121,106,107').split(',').map(Number),
);
const sealMarks = marks.filter((m) => SEAL_IDS.has(m.id));
const c0 = {
  x: sealMarks.reduce((s, m) => s + m.cx, 0) / sealMarks.length,
  y: sealMarks.reduce((s, m) => s + m.cy, 0) / sealMarks.length,
};
// The thorn ring is deleted entirely; the seal is just the tomoe trio,
// centered on its own centroid.
const RING_IDS = new Set(
  marks
    .filter((m) => {
      if (SEAL_IDS.has(m.id)) return false;
      const r = Math.hypot(m.cx - c0.x, m.cy - c0.y);
      return r > 60 && r < 170;
    })
    .map((m) => m.id),
);
console.log(`deleting ${RING_IDS.size} ring fragments`);
const best = { x: c0.x, y: c0.y };

const SEAL_R = 0;
const seal = sealMarks;
const flames = [];
let maxDist = 0;
let minDist = Infinity;
for (const m of marks) {
  if (SEAL_IDS.has(m.id) || RING_IDS.has(m.id)) continue;
  m.dist = Math.hypot(m.cx - best.x, m.cy - best.y);
  if (m.dist > maxDist) maxDist = m.dist;
  if (m.dist < minDist) minDist = m.dist;
  flames.push(m);
}
for (const m of flames)
  m.dist = +(((m.dist - minDist) / (maxDist - minDist))).toFixed(4);

// The traced field is lopsided (source photo bias), so recenter the whole
// flame cloud on the seal. Weight by sqrt(area) so big clusters count more.
const wsum = flames.reduce((a, m) => a + Math.sqrt(m.w * m.h), 0);
const fx = flames.reduce((a, m) => a + m.cx * Math.sqrt(m.w * m.h), 0) / wsum;
const fy = flames.reduce((a, m) => a + m.cy * Math.sqrt(m.w * m.h), 0) / wsum;
const dx = best.x - fx;
const dy = best.y - fy;
const translateD = (d, tx, ty) => {
  let ix = 0;
  return d.replace(/-?\d+(\.\d+)?/g, (num) => {
    const v = parseFloat(num) + (ix++ % 2 === 0 ? tx : ty);
    return String(Math.round(v * 10) / 10);
  });
};
for (const m of flames) {
  // marks inside the ring cluster stay put; the outer field slides over,
  // blended so there is no visible seam at the boundary
  const r = Math.hypot(m.cx - best.x, m.cy - best.y);
  const k = Math.min(1, Math.max(0, (r - 150) / 250));
  if (k > 0) {
    m.d = translateD(m.d, dx * k, dy * k);
    m.cx += dx * k;
    m.cy += dy * k;
  }
}
// distances change after the shift; recompute the stagger field
let max2 = 0;
let min2 = Infinity;
for (const m of flames) {
  m.dist = Math.hypot(m.cx - best.x, m.cy - best.y);
  if (m.dist > max2) max2 = m.dist;
  if (m.dist < min2) min2 = m.dist;
}
for (const m of flames)
  m.dist = +(((m.dist - min2) / (max2 - min2))).toFixed(4);
flames.sort((a, b) => a.dist - b.dist);
console.log(`field recentered by (${dx.toFixed(1)}, ${dy.toFixed(1)})`);
void SEAL_R;
void vh;
flames.sort((a, b) => a.dist - b.dist);

const out = `// Generated by scripts/build-sigil.mjs — do not edit by hand.
export const VIEW = { w: ${vw}, h: ${vh} };
export const SEAL_CENTER = { x: ${best.x.toFixed(1)}, y: ${best.y.toFixed(1)} };

export interface SigilMark {
  id: number;
  d: string;
  cx: number;
  cy: number;
  /** 0..1 normalized distance from the seal; drives ignition stagger */
  dist: number;
}

export const SEAL_PATHS: string[] = ${JSON.stringify(seal.map((m) => m.d))};

export const FLAME_MARKS: SigilMark[] = [
${flames
  .map(
    (m) =>
      `  { id: ${m.id}, cx: ${m.cx.toFixed(1)}, cy: ${m.cy.toFixed(1)}, dist: ${m.dist}, d: ${JSON.stringify(m.d)} },`,
  )
  .join('\n')}
];
`;
writeFileSync(new URL('../src/sigil.ts', import.meta.url), out);
console.log(
  `seal center (${best.x.toFixed(0)}, ${best.y.toFixed(0)}) | ${seal.length} seal paths | ${flames.length} flame marks`,
);
